-- AI_UTENTI_Save: upsert utente. La password si imposta SOLO passando @NuovaPassword
-- (hash MD5 server-side, come AI_AuthLogin). In update, se @NuovaPassword e' NULL la Pass resta invariata.
CREATE OR ALTER PROCEDURE dbo.AI_UTENTI_Save
    @IdUtente int = NULL,
    @Utente varchar(100) = NULL,
    @Email varchar(50) = NULL,
    @Nome varchar(50) = NULL,
    @CodiceFiscale varchar(16) = NULL,
    @IdRuolo int = NULL,
    @IdUtentePadre int = NULL,
    @LoginErrors int = NULL,
    @DataUltimoAccesso datetime = NULL,
    @IdFiliale int = NULL,
    @DataInizio smalldatetime = NULL,
    @DataFine smalldatetime = NULL,
    @RECHASH varchar(50) = NULL,
    @RECDATA datetime = NULL,
    @IdCliente int = NULL,
    @codAppLogin varchar(50) = NULL,
    @IdMezzo_Default int = NULL,
    @CodPoste varchar(50) = NULL,
    @CodADER4 varchar(8) = NULL,
    @Telefono varchar(50) = NULL,
    @CERT_ProfiloCertificatore smalldatetime = NULL,
    @CERT_CertificatoValido smalldatetime = NULL,
    @CERT_IdUtenteCertificatore int = NULL,
    @CERT_Alias varchar(50) = NULL,
    @CERT_PIN varchar(50) = NULL,
    @CERT_Tentativi int = NULL,
    @CERT_StatoNascita varchar(2) = NULL,
    @CERT_uniqueidentifier varchar(50) = NULL,
    @CERT_DataRevoca smalldatetime = NULL,
    @CERT_DataSospensione smalldatetime = NULL,
    @CERT_SerialNumber varchar(50) = NULL,
    @CERT_DataScadenza smalldatetime = NULL,
    @CERT_TempSospeso smalldatetime = NULL,
    @CodADER varchar(10) = NULL,
    @FotoTessera varchar(2000) = NULL,
    @FirmaEstesa varchar(2000) = NULL,
    @FirmaSigla varchar(2000) = NULL,
    @flagFirma int = NULL,
    @idAziendaFatt int = NULL,
    @Partime float = NULL,
    @IndirizzoRes varchar(250) = NULL,
    @CapRes varchar(50) = NULL,
    @ComuneRes varchar(250) = NULL,
    @ProvRes varchar(50) = NULL,
    @Matricola varchar(50) = NULL,
    @DataNascita date = NULL,
    @GiorniLavorativi varchar(50) = NULL,
    @OrarioLavoro varchar(50) = NULL,
    @Livello varchar(50) = NULL,
    @Mansione varchar(50) = NULL,
    @Iban varchar(50) = NULL,
    @NumeroScarpe varchar(50) = NULL,
    @TagliaAbbigliamento varchar(50) = NULL,
    @Note varchar(50) = NULL,
    @Stato varchar(50) = NULL,
    @Colore varchar(50) = NULL,
    @Cod_iMile varchar(100) = NULL,
    @tokenAutoLogin varchar(50) = NULL,
    @tokenRegistrazione varchar(50) = NULL,
    @Cittadinanza varchar(100) = NULL,
    @LuogoNascita varchar(100) = NULL,
    @TitoloStudio varchar(100) = NULL,
    @TipoContratto varchar(100) = NULL,
    @DataFineContratto date = NULL,
    @OreSettimanali decimal(4,1) = NULL,
    @CCNL varchar(100) = NULL,
    @SoggiornoTipo varchar(100) = NULL,
    @SoggiornoNumero varchar(100) = NULL,
    @SoggiornoMotivo varchar(100) = NULL,
    @SoggiornoScadenza date = NULL,
    @SoggiornoQuestura varchar(100) = NULL,
    @UnilavCodice varchar(100) = NULL,
    @UnilavData datetime = NULL,
    @NuovaPassword varchar(250) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @hash varchar(32) = CASE WHEN @NuovaPassword IS NULL THEN NULL
        ELSE CONVERT(char(32), HASHBYTES('MD5', @NuovaPassword), 2) END;
    IF @IdUtente IS NULL OR @IdUtente = 0
    BEGIN
        INSERT INTO [UTENTI] ([Utente], [Email], [Nome], [CodiceFiscale], [IdRuolo], [IdUtentePadre], [LoginErrors], [DataUltimoAccesso], [IdFiliale], [DataInizio], [DataFine], [RECHASH], [RECDATA], [IdCliente], [codAppLogin], [IdMezzo_Default], [CodPoste], [CodADER4], [Telefono], [CERT_ProfiloCertificatore], [CERT_CertificatoValido], [CERT_IdUtenteCertificatore], [CERT_Alias], [CERT_PIN], [CERT_Tentativi], [CERT_StatoNascita], [CERT_uniqueidentifier], [CERT_DataRevoca], [CERT_DataSospensione], [CERT_SerialNumber], [CERT_DataScadenza], [CERT_TempSospeso], [CodADER], [FotoTessera], [FirmaEstesa], [FirmaSigla], [flagFirma], [idAziendaFatt], [Partime], [IndirizzoRes], [CapRes], [ComuneRes], [ProvRes], [Matricola], [DataNascita], [GiorniLavorativi], [OrarioLavoro], [Livello], [Mansione], [Iban], [NumeroScarpe], [TagliaAbbigliamento], [Note], [Stato], [Colore], [Cod_iMile], [tokenAutoLogin], [tokenRegistrazione], [Cittadinanza], [LuogoNascita], [TitoloStudio], [TipoContratto], [DataFineContratto], [OreSettimanali], [CCNL], [SoggiornoTipo], [SoggiornoNumero], [SoggiornoMotivo], [SoggiornoScadenza], [SoggiornoQuestura], [UnilavCodice], [UnilavData], [Pass])
        VALUES (@Utente, @Email, @Nome, @CodiceFiscale, @IdRuolo, @IdUtentePadre, @LoginErrors, @DataUltimoAccesso, @IdFiliale, @DataInizio, @DataFine, @RECHASH, @RECDATA, @IdCliente, @codAppLogin, @IdMezzo_Default, @CodPoste, @CodADER4, @Telefono, @CERT_ProfiloCertificatore, @CERT_CertificatoValido, @CERT_IdUtenteCertificatore, @CERT_Alias, @CERT_PIN, @CERT_Tentativi, @CERT_StatoNascita, @CERT_uniqueidentifier, @CERT_DataRevoca, @CERT_DataSospensione, @CERT_SerialNumber, @CERT_DataScadenza, @CERT_TempSospeso, @CodADER, @FotoTessera, @FirmaEstesa, @FirmaSigla, @flagFirma, @idAziendaFatt, @Partime, @IndirizzoRes, @CapRes, @ComuneRes, @ProvRes, @Matricola, @DataNascita, @GiorniLavorativi, @OrarioLavoro, @Livello, @Mansione, @Iban, @NumeroScarpe, @TagliaAbbigliamento, @Note, @Stato, @Colore, @Cod_iMile, @tokenAutoLogin, @tokenRegistrazione, @Cittadinanza, @LuogoNascita, @TitoloStudio, @TipoContratto, @DataFineContratto, @OreSettimanali, @CCNL, @SoggiornoTipo, @SoggiornoNumero, @SoggiornoMotivo, @SoggiornoScadenza, @SoggiornoQuestura, @UnilavCodice, @UnilavData, @hash);
        SELECT CAST(SCOPE_IDENTITY() AS int) AS id;
    END
    ELSE
    BEGIN
        UPDATE [UTENTI] SET
            [Utente] = @Utente,
            [Email] = @Email,
            [Nome] = @Nome,
            [CodiceFiscale] = @CodiceFiscale,
            [IdRuolo] = @IdRuolo,
            [IdUtentePadre] = @IdUtentePadre,
            [LoginErrors] = @LoginErrors,
            [DataUltimoAccesso] = @DataUltimoAccesso,
            [IdFiliale] = @IdFiliale,
            [DataInizio] = @DataInizio,
            [DataFine] = @DataFine,
            [RECHASH] = @RECHASH,
            [RECDATA] = @RECDATA,
            [IdCliente] = @IdCliente,
            [codAppLogin] = @codAppLogin,
            [IdMezzo_Default] = @IdMezzo_Default,
            [CodPoste] = @CodPoste,
            [CodADER4] = @CodADER4,
            [Telefono] = @Telefono,
            [CERT_ProfiloCertificatore] = @CERT_ProfiloCertificatore,
            [CERT_CertificatoValido] = @CERT_CertificatoValido,
            [CERT_IdUtenteCertificatore] = @CERT_IdUtenteCertificatore,
            [CERT_Alias] = @CERT_Alias,
            [CERT_PIN] = @CERT_PIN,
            [CERT_Tentativi] = @CERT_Tentativi,
            [CERT_StatoNascita] = @CERT_StatoNascita,
            [CERT_uniqueidentifier] = @CERT_uniqueidentifier,
            [CERT_DataRevoca] = @CERT_DataRevoca,
            [CERT_DataSospensione] = @CERT_DataSospensione,
            [CERT_SerialNumber] = @CERT_SerialNumber,
            [CERT_DataScadenza] = @CERT_DataScadenza,
            [CERT_TempSospeso] = @CERT_TempSospeso,
            [CodADER] = @CodADER,
            [FotoTessera] = @FotoTessera,
            [FirmaEstesa] = @FirmaEstesa,
            [FirmaSigla] = @FirmaSigla,
            [flagFirma] = @flagFirma,
            [idAziendaFatt] = @idAziendaFatt,
            [Partime] = @Partime,
            [IndirizzoRes] = @IndirizzoRes,
            [CapRes] = @CapRes,
            [ComuneRes] = @ComuneRes,
            [ProvRes] = @ProvRes,
            [Matricola] = @Matricola,
            [DataNascita] = @DataNascita,
            [GiorniLavorativi] = @GiorniLavorativi,
            [OrarioLavoro] = @OrarioLavoro,
            [Livello] = @Livello,
            [Mansione] = @Mansione,
            [Iban] = @Iban,
            [NumeroScarpe] = @NumeroScarpe,
            [TagliaAbbigliamento] = @TagliaAbbigliamento,
            [Note] = @Note,
            [Stato] = @Stato,
            [Colore] = @Colore,
            [Cod_iMile] = @Cod_iMile,
            [tokenAutoLogin] = @tokenAutoLogin,
            [tokenRegistrazione] = @tokenRegistrazione,
            [Cittadinanza] = @Cittadinanza,
            [LuogoNascita] = @LuogoNascita,
            [TitoloStudio] = @TitoloStudio,
            [TipoContratto] = @TipoContratto,
            [DataFineContratto] = @DataFineContratto,
            [OreSettimanali] = @OreSettimanali,
            [CCNL] = @CCNL,
            [SoggiornoTipo] = @SoggiornoTipo,
            [SoggiornoNumero] = @SoggiornoNumero,
            [SoggiornoMotivo] = @SoggiornoMotivo,
            [SoggiornoScadenza] = @SoggiornoScadenza,
            [SoggiornoQuestura] = @SoggiornoQuestura,
            [UnilavCodice] = @UnilavCodice,
            [UnilavData] = @UnilavData,
            [Pass] = CASE WHEN @NuovaPassword IS NULL THEN [Pass] ELSE @hash END
        WHERE [IdUtente] = @IdUtente;
        SELECT @IdUtente AS id;
    END
END
