-- Verifica degli oggetti che gli script di sql-nuove creano (stored AI_/WF_,
-- viste, tabelle, tipi): elenca quelli che sul server mancano, con lo script
-- che li crea. Generato dal fork il 2026-09-07 leggendo gli script; da rigenerare
-- se si aggiungono script (basta rilanciare la stessa ricognizione).
USE DeliveryDB;
GO
SET NOCOUNT ON;
DECLARE @attesi TABLE (Nome SYSNAME, Tipo VARCHAR(20), Script VARCHAR(100));
INSERT INTO @attesi (Nome, Tipo, Script) VALUES
    ('AI_AZIENDE_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_AttivitaDipendenti_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_AttivitaFiliali_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_AuthLogin', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_Azioni_SaveAzione', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_Azioni_SaveProcessoAzione', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_Azioni_SaveWorkflow', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_CLIENTI_CONDIZIONI_Del', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_CLIENTI_CONDIZIONI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_CLIENTI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_ElencoMenuGruppi', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_FATT_LISTINI_Del', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_FATT_LISTINI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_FILE_LOAD_Insert', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_FILE_TRACCIATO_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_FILIALI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_FORNITORI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_GEO_COPERTURE_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_GEO_CreaGiro', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_GEO_CreaGiroDaComuni', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_GRUPPI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_INTERROGAZIONI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_LISTA_VALORI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_MENU_Del', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_MENU_Duplica', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_MENU_ELEMENTIGRUPPI_Add', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_MENU_ELEMENTIGRUPPI_Del', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_MENU_ELEMENTI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_MITTENTI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_PROCESSI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_PRODOTTI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_SPED_AZIONI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_SPED_AccettazioneBanco', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_SPED_NuovaParcel', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_SPED_STATI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_SPED_VideoCodifica_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_SPED_WORKFLOW_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_FILIALI_Add', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_FILIALI_Del', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_GRUPPI_Add', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_GRUPPI_Del', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_PROCESSI_Add', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_PROCESSI_Del', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_PROFILI_Add', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_PROFILI_Del', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_Save', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_UTENTI_Unilav_Applica', 'PROCEDURE', '00_crea_tutto.sql'),
    ('AI_MEZZI_AssegnaDriver', 'PROCEDURE', 'AI_MEZZI_AssegnaDriver.sql'),
    ('AI_MEZZI_NOTE_Save', 'PROCEDURE', 'AI_MEZZI_NOTE_Save.sql'),
    ('AI_MEZZI_SINISTRI_Save', 'PROCEDURE', 'AI_MEZZI_SINISTRI_Save.sql'),
    ('AI_UTENTI_ATTIVITA_PulisciVuote', 'PROCEDURE', 'AI_UTENTI_ATTIVITA_PulisciVuote.sql'),
    ('AI_UTENTI_CambiaPassword', 'PROCEDURE', 'AI_UTENTI_CambiaPassword.sql'),
    ('AI_UTENTI_Del', 'PROCEDURE', 'AI_UTENTI_Del.sql'),
    ('AI_UTENTI_Stato_Save', 'PROCEDURE', 'AI_UTENTI_Stato_Save.sql'),
    ('AUTO_Sched_ORE_01', 'PROCEDURE', 'AUTO_Sched_ORE_01_fix.sql'),
    ('AUTO_Sched_OgniOra', 'PROCEDURE', 'AUTO_Sched_OgniOra_fix.sql'),
    ('AI_LOG_Exec_Add', 'PROCEDURE', 'FATT_Tipo_Fatturazione.sql'),
    ('FATT_ALIA_Genera', 'PROCEDURE', 'FATT_Tipo_Fatturazione.sql'),
    ('FATT_ALIA_Previsione', 'PROCEDURE', 'FATT_Tipo_Fatturazione.sql'),
    ('FATT_ANCI_Genera', 'PROCEDURE', 'FATT_Tipo_Fatturazione.sql'),
    ('FATT_ANCI_Previsione', 'PROCEDURE', 'FATT_Tipo_Fatturazione.sql'),
    ('FATT_TIPO_Genera', 'PROCEDURE', 'FATT_Tipo_Fatturazione.sql'),
    ('FATT_TIPO_Previsione', 'PROCEDURE', 'FATT_Tipo_Fatturazione.sql'),
    ('InserimentoEsiti', 'PROCEDURE', 'InserimentoEsiti_fix_ADER4.sql'),
    ('LoadFromFile', 'PROCEDURE', 'LoadFromFile_fix.sql'),
    ('AI_MEZZI_KM_Correggi', 'PROCEDURE', 'MEZZI_km_correzioni.sql'),
    ('MEZZI_KM_CORREZIONI', 'TABLE', 'MEZZI_km_correzioni.sql'),
    ('AI_MEZZI_Save', 'PROCEDURE', 'MEZZI_scheda.sql'),
    ('AI_PALMARI_Filiale', 'PROCEDURE', 'PALMARI_filiale_tag.sql'),
    ('AI_PALMARI_Del', 'PROCEDURE', 'PALMARI_tabelle.sql'),
    ('AI_PALMARI_Import', 'PROCEDURE', 'PALMARI_tabelle.sql'),
    ('AI_PALMARI_POSIZIONE_Save', 'PROCEDURE', 'PALMARI_tabelle.sql'),
    ('AI_PALMARI_Save', 'PROCEDURE', 'PALMARI_tabelle.sql'),
    ('PALMARI', 'TABLE', 'PALMARI_tabelle.sql'),
    ('PALMARI_POSIZIONI', 'TABLE', 'PALMARI_tabelle.sql'),
    ('PALMARI_VARIAZIONI', 'TABLE', 'PALMARI_tabelle.sql'),
    ('V_Palmari', 'VIEW', 'PALMARI_tabelle.sql'),
    ('PALM_ELABORA_BATCH_LOGIN', 'PROCEDURE', 'PALM_ELABORA_BATCH_LOGIN_fix.sql'),
    ('PALM_ELABORA_BATCH', 'PROCEDURE', 'PALM_ELABORA_BATCH_fix.sql'),
    ('RicercaBarcode', 'PROCEDURE', 'RicercaBarcode_fix_url.sql'),
    ('AI_SIM_Save', 'PROCEDURE', 'SIM_assegnazioni.sql'),
    ('V_Sim', 'VIEW', 'SIM_assegnazioni.sql'),
    ('AI_SIM_Del', 'PROCEDURE', 'SIM_tabelle.sql'),
    ('AI_SIM_Import', 'PROCEDURE', 'SIM_tabelle.sql'),
    ('AI_SIM_RILEVAZIONE_Save', 'PROCEDURE', 'SIM_tabelle.sql'),
    ('SIM', 'TABLE', 'SIM_tabelle.sql'),
    ('SIM_RILEVAZIONI', 'TABLE', 'SIM_tabelle.sql'),
    ('SIM_VARIAZIONI', 'TABLE', 'SIM_tabelle.sql'),
    ('Tracking', 'PROCEDURE', 'Tracking_fix_url.sql'),
    ('UTENTI_AttivitaMancanti', 'PROCEDURE', 'UTENTI_AttivitaMancanti_interni.sql'),
    ('WF_Esecuzione', 'TABLE', 'WF_database.sql'),
    ('WF_EsecuzioneLog', 'TABLE', 'WF_database.sql'),
    ('WF_PianificazioneDettaglio', 'TABLE', 'WF_database.sql'),
    ('WF_PianificazioneMaster', 'TABLE', 'WF_database.sql'),
    ('WF_StatoEsecuzione', 'TABLE', 'WF_database.sql'),
    ('WF_TipoStep', 'TABLE', 'WF_database.sql'),
    ('WF_Workflow', 'TABLE', 'WF_database.sql'),
    ('WF_WorkflowStep', 'TABLE', 'WF_database.sql'),
    ('WF_udt_StepList', 'TYPE', 'WF_database.sql'),
    ('WF_usp_Dettaglio_Elimina', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Dettaglio_Salva', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_EsecuzioneLog_Add', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Esecuzione_Annulla', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Esecuzione_Avanzamento', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Esecuzione_Claim', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Esecuzione_Crea', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Esecuzione_Inizia', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Esecuzione_Pianifica', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Esecuzione_Termina', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Pianificazione_Elimina', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Pianificazione_Salva', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Step_Delete', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Step_Insert', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Step_Sposta', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Step_UpdateParametri', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Workflow_Delete', 'PROCEDURE', 'WF_database.sql'),
    ('WF_usp_Workflow_Import', 'PROCEDURE', 'WF_database.sql'),
    ('WF_vw_Esecuzione', 'VIEW', 'WF_database.sql'),
    ('WF_vw_WorkflowStepAlbero', 'VIEW', 'WF_database.sql'),
    ('WF_usp_Workflow_Salva', 'PROCEDURE', 'WF_stored_raiserror.sql');
SELECT a.Script, a.Tipo, a.Nome,
       CASE WHEN o.object_id IS NOT NULL OR t.user_type_id IS NOT NULL THEN 'presente' ELSE 'MANCA' END AS Stato
FROM @attesi a
LEFT JOIN sys.objects o ON o.name = a.Nome AND o.schema_id = SCHEMA_ID('dbo')
LEFT JOIN sys.types t ON t.name = a.Nome AND a.Tipo = 'TYPE'
ORDER BY CASE WHEN o.object_id IS NULL AND t.user_type_id IS NULL THEN 0 ELSE 1 END, a.Script, a.Nome;
GO
